# Generated by Django 4.2.8 on 2023-12-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(max_length=2097152, upload_to=''),
        ),
    ]
